versions:
  v0.2.1:
    folder: all
  v0.2.2:
    folder: all
  v0.2.3:
    folder: all
  v0.2.4:
    folder: all
  v0.2.5:
    folder: all
  v0.2.6:
    folder: all
  v0.2.7:
    folder: all
  v0.2.8:
    folder: all
  v0.2.9:
    folder: all
