---
# To be triggered on release published. It will create a PR with the new version
name: "Published Release"

on:
  workflow_call:
    inputs:
      github_sha:
        type: string
        required: true
      library_name:
        type: string
        required: true
      repository:
        type: string
        required: true
    secrets:
      APP_RECIPES_APP_ID:
        required: true
      APP_RECIPES_PRIVATE_KEY:
        required: true

jobs:
  pr_to_recipes:
    runs-on: ubuntu-latest
    steps:
      - name: "Print information"
        run: |
          echo "github_sha: ${{ inputs.github_sha }}"
          echo "library_name: ${{ inputs.library_name }}"
          echo "repository: ${{ inputs.repository }}"

      - name: Checkout recipes repository
        uses: actions/checkout@v2
        with:
          repository: 'jgsogo/conan-recipes'
          ref: 'master'

      - name: Add version to repo files
        run: |
          python .github/scripts/add_version.py --name=${{ inputs.library_name }} --version=${{ inputs.github_sha }}
          echo "Not implemented yet" >> README.md
          git diff

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_RECIPES_APP_ID }}
          private_key: ${{ secrets.APP_RECIPES_PRIVATE_KEY }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "[${{ inputs.library_name }}] Add version ${{ inputs.github_sha }}"
          branch: "${{ inputs.library_name }}-${{ inputs.github_sha }}"
          title: "[${{ inputs.library_name }}] Add version ${{ inputs.github_sha }}"
          body: "[**${{ inputs.library_name }}**](https://github.com/${{ inputs.repository }}): add version `${{ inputs.github_sha }}`."
          reviewers: "jgsogo"
          token: ${{ steps.generate-token.outputs.token }}
