---
# Test the recipe that belongs to a given repository
name: "(Chunk) Test Conan recipe"

on:
  workflow_call:
    inputs:
      docker_image:
        type: string
        required: false
        default: conanio/gcc10:1.43.3  # TODO: Use new docker images (gcc10)
      repository:
        type: string
        required: true
      github_sha:
        type: string
        required: true
      library_name:
        type: string
        required: true


env:
  CONAN_USER_HOME: /home/conan

defaults:
  run:
    working-directory: /home/conan

jobs:
  test_conan_package:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.docker_image }}
    env:
      CONAN_USER_HOME: /home/conan
    steps:
      - name: Check out repository code
        uses: rodrigorodriguescosta/checkout@1d64c0a4a695ff5edb95596c11b430050668c83f  # FIXME: Not using actions/checkout just because of 'https://github.com/actions/checkout/pull/388'
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.github_sha }}
          path: /home/conan/library

      - name: Check out recipes repository
        uses: rodrigorodriguescosta/checkout@1d64c0a4a695ff5edb95596c11b430050668c83f  # FIXME: Not using actions/checkout just because of 'https://github.com/actions/checkout/pull/388'
        with:
          repository: jgsogo/conan-recipes
          path: /home/conan/conan-recipes

      - name: Configure Conan
        run: |
          conan config set general.revisions_enabled=1
          conan config install https://github.com/conan-io/conanclientcert.git
          conan --version
          conan config home

      - name: Connect to remote
        run: |
          conan remote add sogo https://sogo.jfrog.io/artifactory/api/conan/conan-center

      - name: Copy settings to cache
        run: |
          cp conan-recipes/.conan/settings.yml /home/conan/.conan/settings.yml

      - name: Add version to conandata.yml
        run: |
            echo "  \"${{ github.sha }}\":" >> conan-recipes/recipes/${{ inputs.library_name }}/all/conandata.yml
            echo "    url: https://github.com/${{ inputs.repository }}/archive/${{ inputs.github_sha }}.zip" >> conan-recipes/recipes/${{ inputs.library_name }}/all/conandata.yml
            cat conan-recipes/recipes/${{ inputs.library_name }}/all/conandata.yml

      - name: Run create
        run: |
          for profile in conan-recipes/.conan/profiles/* ; do
            conan create conan-recipes/recipes/${{ inputs.library_name }}/all/conanfile.py ${{ inputs.library_name }}/${{ inputs.github_sha }}@jgsogo/testing --profile:host=$profile --profile:build=default
          done
