name: Full CI
on: [push]
jobs:
  build_missing:
    runs-on: ubuntu-latest
    container:
      image: conanio/gcc11-ubuntu16.04:1.44.0
    env:
      CONAN_USER_HOME: /home/conan
    steps:
      - name: Check out repository code
        # uses: actions/checkout@v2
        working-directory: /home/conan
        run: |
          git clone https://github.com/${{ github.repository }}.git
          cd ${{ github.event.repository.name }}
          git checkout ${{ github.ref_name }}

      - name: Cache Conan packages
        uses: actions/cache@v2
        with:
          key: conan-cache-${{ github.repository }}
          path: /home/conan/.conan

      - name: Configure Conan
        run: |
          conan config set general.revisions_enabled=1
          conan config install https://github.com/conan-io/conanclientcert.git
          conan --version
          conan config home

      - name: Copy configuration to cache
        working-directory: /home/conan/${{ github.event.repository.name }}
        run: |
          cp -r .conan/profiles /home/conan/.conan
          conan profile list

      - name: Export all recipes
        working-directory: /home/conan/${{ github.event.repository.name }}
        run: |
          for d in recipes/* ; do
            python .github/scripts/parse_config_yml.py $d/config.yml | while read -r folder version ; do 
              conan export "$d/$folder/conanfile.py" $version@jgsogo/stable
            done
          done

      - name: Build all recipes
        working-directory: /home/conan/${{ github.event.repository.name }}
        run: |
          for profile in .conan/profiles/* ; do
            for d in recipes/* ; do
              python .github/scripts/parse_config_yml.py $d/config.yml | while read -r folder version ; do 
                echo "****************************************"
                echo "conan create \"$d/$folder/conanfile.py\" $version@jgsogo/stable --build=missing --profile:host=$profile --profile:build=default"
                echo "****************************************"
                conan create "$d/$folder/conanfile.py" $version@jgsogo/stable --build=missing --profile:host=$profile --profile:build=default
              done
            done
          done

      - name: Clean cache
        run: |
          conan remove "*" --builds --force
          conan remove "*" --src --force
