---
# Export and build-missing all recipes
name: Full CI
on:
  workflow_dispatch:
  schedule:
    # Trigger every Friday at 9:00
    - cron: "0 9 * * 5"
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CONAN_USER_HOME: /home/conan
  CONAN_SYSREQUIRES_MODE: enabled
  CONAN_PRINT_RUN_COMMANDS: 1

defaults:
  run:
    working-directory: /home/conan/conan-recipes

jobs:
  build_all_recipes:
    runs-on: ubuntu-latest
    container:
      image: conanio/gcc11-ubuntu16.04:1.46.2
    steps:

      - name: Install jq
        working-directory: /home/conan
        run: |
          sudo apt-get update
          sudo apt-get install jq -y

      - name: Check out repository code
        uses: rodrigorodriguescosta/checkout@1d64c0a4a695ff5edb95596c11b430050668c83f  # FIXME: Not using actions/checkout just because of 'https://github.com/actions/checkout/pull/388'
        with:
          path: /home/conan/conan-recipes

      - name: Cache Conan packages
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-jgsogo-${{ github.event.repository.name }}
          path: /home/conan/.conan

      - name: Configure Conan
        run: |
          conan config set general.revisions_enabled=1
          conan config install https://github.com/conan-io/conanclientcert.git
          conan --version
          conan config home

      - name: Connect to remote
        run: |
          conan remote add -i 0 sogo https://sogo.jfrog.io/artifactory/api/conan/conan-center
          conan user -r sogo -p ${{secrets.RT_TOKEN}} ${{secrets.RT_USERNAME}}

      - name: Copy settings to cache
        run: |
          cp .conan/settings.yml /home/conan/.conan/settings.yml

      - name: Export all recipes
        run: |
          for d in recipes/* ; do
            python .github/scripts/parse_config_yml.py $d/config.yml | while read -r folder version ; do 
              conan export "$d/$folder/conanfile.py" $version@jgsogo/stable
            done
          done

      - name: Build all recipes
        run: |
          for profile in .conan/profiles/* ; do
            cd recipes
            for d in * ; do
              python ../.github/scripts/parse_config_yml.py $d/config.yml | while read -r folder version ; do 
                echo "****************************************"
                echo "folder: $folder, name: $d, version: $version"
                echo "conan install $d/$version@jgsogo/stable --build=missing --profile:host=$profile --profile:build=default"
                echo "conan test \"$d/$folder/test_package/conanfile.py\" $d/$version@jgsogo/stable --build=missing --profile:host=$profile --profile:build=default"
                echo "****************************************"
                conan info $d/$version@jgsogo/stable --profile:host=../$profile --profile:build=default --json=../$d-$version-$profile.json
                conan install $d/$version@jgsogo/stable --build=missing --profile:host=../$profile --profile:build=default || (($?==6 ? 1 : 0))
                conan test "$d/$folder/test_package/conanfile.py" $d/$version@jgsogo/stable --build=missing --profile:host=../$profile --profile:build=default
              done
            done
            cd ..
          done

      - name: Upload only packages built
        # Upload only the packages that were built (they should be only ones in _host_ context)
        if: github.ref == 'refs/heads/master'
        run: |
          for profile in .conan/profiles/* ; do
            cd recipes
            for d in * ; do
              python ../.github/scripts/parse_config_yml.py $d/config.yml | while read -r folder version ; do 
                jq '.[] | select( .context=="host") | select( .binary=="Missing") | .reference' ../$d-$version-$profile.json | while read -r reference ; do
                  ref_unquoted=$(echo $reference | sed 's/\"//g')
                  ref_usable=$(echo $ref_unquoted | sed '/@/!s/.*/&@/g')
                  conan upload --confirm --parallel --all --remote sogo $ref_usable
                done
              done
            done
            cd ..
          done
          
      - name: Clean cache
        run: |
          conan remove "*" --builds --force
          conan remove "*" --src --force
