---
# Export and build-missing all recipes
name: Full CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CONAN_USER_HOME: /home/conan

jobs:
  build_all_recipes:
    runs-on: ubuntu-latest
    container:
      image: conanio/gcc11-ubuntu16.04:1.44.0
    steps:
      - name: Upgrade Git version
        run: |
          mkdir git-install && cd git-install
          sudo apt-get update
          sudo apt-get install unzip -y
          wget https://github.com/git/git/archive/v2.34.1.zip -O git.zip
          unzip git.zip
          cd git-*
          make prefix=/usr/local all
          sudo make prefix=/usr/local install
          git --version

      - uses: actions/checkout@v2

      - name: Cache Conan packages
        uses: actions/cache@v2
        with:
          key: conan-cache-${{ github.repository }}
          path: /home/conan/.conan

      - name: Configure Conan
        run: |
          conan config set general.revisions_enabled=1
          conan config install https://github.com/conan-io/conanclientcert.git
          conan --version
          conan config home

      - name: Connect to remote
        run: |
          conan remote add sogo https://sogo.jfrog.io/artifactory/api/conan/conan-center
          conan user -r sogo -p ${{secrets.RT_TOKEN}} ${{secrets.RT_USERNAME}}

      #- name: Copy configuration to cache
      #  run: |
      #    cp -r .conan/profiles /home/conan/.conan
      #    conan profile list

      - name: Export all recipes
        run: |
          for d in recipes/* ; do
            python .github/scripts/parse_config_yml.py $d/config.yml | while read -r folder version ; do 
              conan export "$d/$folder/conanfile.py" $version@jgsogo/stable
            done
          done

      - name: Build all recipes
        run: |
          for profile in .conan/profiles/* ; do
            for d in recipes/* ; do
              python .github/scripts/parse_config_yml.py $d/config.yml | while read -r folder version ; do 
                echo "****************************************"
                echo "conan create \"$d/$folder/conanfile.py\" $version@jgsogo/stable --build=missing --profile:host=$profile --profile:build=default"
                echo "****************************************"
                conan create "$d/$folder/conanfile.py" $version@jgsogo/stable --build=missing --profile:host=$profile --profile:build=default
              done
            done
          done

      - name: Upload to remote
        run: |
          conan upload --confirm --parallel --all --remote sogo "*"

      - name: Clean cache
        run: |
          conan remove "*" --builds --force
          conan remove "*" --src --force
