name: Keep RT alive

on:
  schedule:
    # Trigger every sunday at 9:00
    - cron: "0 9 * * 0"

env:
  CONAN_USER_HOME: /home/conan
  CONAN_SYSREQUIRES_MODE: enabled
  CONAN_PRINT_RUN_COMMANDS: 1
  
defaults:
  run:
    working-directory: /home/conan/conan-recipes

jobs:
  keep_rt_alive:
    runs-on: ubuntu-latest
    container:
      image: conanio/gcc10:1.43.3  # TODO: Use new docker images (gcc10)
    steps:
      - uses: rodrigorodriguescosta/checkout@1d64c0a4a695ff5edb95596c11b430050668c83f  # FIXME: Not using actions/checkout just because of 'https://github.com/actions/checkout/pull/388'
        with:
          path: /home/conan/conan-recipes

      - name: Configure Conan
        run: |
          conan config set general.revisions_enabled=1
          conan config install https://github.com/conan-io/conanclientcert.git
          conan --version
          conan config home

      - name: Connect to remote
        run: |
          conan remote add -i 0 sogo https://sogo.jfrog.io/artifactory/api/conan/conan-center
          conan user -r sogo -p ${{secrets.RT_TOKEN}} ${{secrets.RT_USERNAME}}

      - name: Create package
        working-directory: /home/conan
        run: |
          conan remove --force --remote sogo template-cpp-project/0.1.0@jgsogo/scheduled
          conan create recipes/template-cpp-project/0.1.0@jgsogo/scheduled --build=missing --profile:host=.conan/profiles/cpp20 --profile:build=default
          conan upload --confirm --all --remote sogo keep_rt_alive/version@jgsogo/scheduled
