name: Keep RT alive

on:
  schedule:
    # Trigger every sunday
    - cron: "* * * * 0"

env:
  CONAN_USER_HOME: /home/conan

defaults:
  run:
    working-directory: /home/conan/conan-recipes

jobs:
  keep_rt_alive:
    runs-on: ubuntu-latest
    container:
      image: conanio/gcc11-ubuntu16.04:1.44.0
    steps:
      - name: Upgrade Git version
        working-directory: /home/conan
        run: |
          sudo apt-get update
          sudo apt-get install software-properties-common -y
          sudo add-apt-repository ppa:git-core/ppa -y
          sudo apt-get update
          sudo apt-get install git -y

      - uses: rodrigorodriguescosta/checkout@1d64c0a4a695ff5edb95596c11b430050668c83f  # FIXME: Not using actions/checkout just because of 'https://github.com/actions/checkout/pull/388'
        with:
          path: /home/conan/conan-recipes

      - name: Configure Conan
        run: |
          conan config set general.revisions_enabled=1
          conan config install https://github.com/conan-io/conanclientcert.git
          conan --version
          conan config home

      - name: Connect to remote
        run: |
          conan remote add sogo https://sogo.jfrog.io/artifactory/api/conan/conan-center
          conan user -r sogo -p ${{secrets.RT_TOKEN}} ${{secrets.RT_USERNAME}}

      - name: Create package
        working-directory: /home/conan
        run: |
          conan remove --force --remote sogo template-cpp-project/0.1.0@jgsogo/scheduled
          conan create recipes/template-cpp-project/0.1.0@jgsogo/scheduled --build=missing --profile:host=.conan/profiles/cpp20 --profile:build=default
          conan upload --confirm --all --remote sogo keep_rt_alive/version@jgsogo/scheduled
